# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    working_directory: /go/src/github.com/jensneuse/graphql-go-tools
    steps:
    - checkout
    - run: go get -u github.com/alecthomas/gometalinter
    - run: gometalinter --install
    - run: gometalinter --config ./gometalinter.json ./pkg/**
    - run: go get -u golang.org/x/tools/cmd/cover
    - run: go get -u github.com/mattn/goveralls
    - run: go test -v -covermode=count -coverprofile=coverage_temp.out ./...
    - run: cat coverage_temp.out | grep -v "github.com/jensneuse/graphql-go-tools/pkg/document/" > coverage.out
    - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
